### ISSUE TITLE
Supabase Function - Register trips data

### ISSUE THREAD

**Issue by BryanBerger98** [Vehicool-Labs/vehicool-app#13]
### ℹ️ Context

Users need to register their trips while they click on "Start a trip" button. The mobile app will track the user's position during a trip.

Supabase hosting a SQL database, the waypoints cannot be saved on Supabase. That is why a MongoDB database (NoSQL) is used to save the waypoints and a Supabase Function is needed to do the bridge between the mobile application and MongoDB.

### ▶️ Expected behavior

Three functions are needed actually.

A first one that allows the user to create a new trip with the following data:
* Type (personal or professional)
* Creation date
* Owner id
* The departure city
* The departure date and time
This function should authenticate the current user to select the right trip owner id.

A second one that allows the mobile app to send waypoints linked to the current tracked trip. This function should receive the trip id as a parameter and check the owner id to allow the user to update the trip.

A third function that allows the user to stop a trip sending the following data:
* The arrival city
* The arrival date and time
This function should also calculate the time it tooks from the start to the end of the trip and save this data.

### ✅ Todo

- [ ] Create trip function
- [ ] Update trip waypoints function
- [ ] Stop trip function
- [ ] Get Google Maps road and save it to the trip document
